<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Home' => 'Home',
    'The button type "{type}" is not supported.' => 'Il pulsante "{type}" non è supportato.',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler cancellare questo oggetto?',
    'Delete' => 'Cancella',
    'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Visualizzazione {start}-{end} di 1 risultato.|Visualizzazione {start}-{end} di {count} risultati.',
    'Either "name" or "value" must be specified for CDataColumn.' => 'Per CDataColumn deve essere specificato o il "name" o il "value".',
    'No results found.' => 'Nessun risultato trovato.',
    'Not set' => 'Non impostato',
    'Please specify the "attributes" property.' => 'Occorre specificare la proprietà "attributes".',
    'Please specify the "data" property.' => 'Occorre specificare la proprietà "data".',
    'Sort by: ' => 'Ordina per:',
    'The "dataProvider" property cannot be empty.' => 'La proprietà "dataProvider" non può essere vuota.',
    'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'L\'attributo deve essere specificato nel formato "Name:Type:Label", dove "Type" e "Label" sono opzionali.',
    'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'La colonna deve essere specificata nel formato "Name:Type:Label", dove "Type" e "Label" sono opzionali.',
    'The property "itemView" cannot be empty.' => 'La proprietà "itemView" non può essere vuota.',
    'Total 1 result.|Total {count} results.' => 'Totale di 1 risultato.|Totale di {count} risultati.',
    'Update' => 'Aggiorna',
    'View' => 'Vedi',
    '{class} must specify "model" and "attribute" or "name" property values.' => '{class} deve specificare il/i valore/i delle proprietà "model" e "attribute" o "name".',
    'About us'=>'Chi siamo?',
    'Contact'=>'Contatti',
    'Read More'=>'Legge ancora',
    'Login'=>'Entrar',
    'Logout ('.Yii::app()->user->name.')'=>'Salir ('.Yii::app()->user->name.')',
    'Bookings'=>'Prenotazioni',
    'Testimonials'=>'Referenzi',
    'Photos'=>'Foto',
    'Places'=>'Luoghi di Interesse',
    'Accommodations'=>'Alloggio',
    'Share this site with your friends'=>'Condividi questo sito con i tuoi amici.',
    'Tours'=>'Escursioni',
    'The best way to explore Cuba.'=>'Il miglior modo di esplorare Cuba.',
    'Matanzas, Cárdenas, & Varadero'=>'Matanzas, Cárdenas, & Varadero',
    'Havana day tour'=>"Un giorno all'Avana",
    'Trinidad & Cienfuegos '=>'Trinidad & Cienfuegos ',
    'Three cities tour'=>'La gitta delle tre città',
    'Guama and the Bay of Pigs' => 'Guama e la Baia dei Maiali',
    'Havana & Tropicana '=>"L'Avana e Tropicana",
    'Havana and the cannon shot'=>"L'Avana e la cannonata",
    'Just tell us your choices and we will do the rest.'=>'Dicci solo cosa preferisci e noi penseremo al resto.',
    'Some images of Cuba.'=>'Qualche foto di Cuba.',
    'Your opinion means a lot to us.'=>'La tua opinione significa tanto per noi.',
    'The best place to enjoy your stay.'=>'Il posto migliore dove goderti il tuo soggiorno.',
    'Get to know who we are.'=>'Vieni a scoprire chi siamo',
    'Keep in touch. You are our commitment.'=>'Resta in contatto con noi.Tu sei il nostro impegno.',
    'Find us on Tripadvisor'=>'Retrouvez-nous sur Tripadvisor.',
    'People are very happy with our work. Get to know their opinion.'=>'Nos clients s’en vont toujours satisfaits; voyez leurs impressions.' ,
    'All Rights Reserved.'=>'Tous Droits Réservés.',
    'Transfers'=>'Trasferimenti',
    'Follow us on Facebook'=>'Seguici su Facebook',
    'Book tour'=>'Prenotare',
    'Create'=>'Creare',
    'About Cubaoutings'=>'Su Cubaoutings',
    'Name'=>'Nome',
    'subject'=>'Argomento',
    'body'=>'Testo',
    'Submit'=>'Invia',
    'Facebook contacts'=>'Contatti di Facebook',
    'Cellphones'=>'Cellulari',
    'Book Accommodations'=>"Prenota l'alloggio",
    'Fields with <span class="required">*</span> are required.'=>'I campi contrassegnati con <span class="required">*</span> sono obbligatori. ',
    'Email Owner'=>'Email cliente',
    'Question'=>'Richieste',
    'Pax'=>'Numero di persone',
    'Date'=>'Data',
    'Create'=>'Prenota'



    );
