<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Home' => 'Accueil',
    'The button type "{type}" is not supported.' => 'Le type de bouton Â« {type} Â» n\'est pas supportÃ©.',
    'Are you sure you want to delete this item?' => 'Voulez-vous vraiment supprimer cet Ã©lÃ©ment ?',
    'Delete' => 'Supprimer',
    'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Afficher les rÃ©sultats de {start} Ã  {end} (total de {count})',
    'Either "name" or "value" must be specified for CDataColumn.' => 'Soit "name", soit "value" doivent Ãªtre dÃ©finis pour CDataColumn.',
    'No results found.' => 'Aucun rÃ©sultat trouvÃ©.',
    'Not set' => 'Non dÃ©fini',
    'Please specify the "attributes" property.' => 'Veuillez dÃ©finir la propriÃ©tÃ© Â« attributes Â».',
    'Please specify the "data" property.' => 'Veuillez dÃ©finir la propriÃ©tÃ© Â« data Â».',
    'Sort by: ' => 'Trier par : ',
    'The "dataProvider" property cannot be empty.' => 'La propriÃ©tÃ© Â« dataProvider Â» ne peut Ãªtre vide.',
    'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'L\'attribut doit Ãªtre dÃ©fini selon le format Â« Name:Type:Label Â», oÃ¹ Â« Type Â» et Â« Label Â» sont optionnels.',
    'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'La colonne doit Ãªtre dÃ©finie selon le format Â« Name:Type:Label Â», oÃ¹ Â« Type Â» et Â« Label Â» sont optionnels.',
    'The property "itemView" cannot be empty.' => 'La propriÃ©tÃ© Â« itemView Â» ne peut Ãªtre vide.',
    'Total 1 result.|Total {count} results.' => 'Total de 1 rÃ©sultat.|Total de {count} rÃ©sultats.',
    'Update' => 'Mettre Ã  jour',
    'View' => 'Voir',
    '{class} must specify "model" and "attribute" or "name" property values.' => '{class} doit dÃ©finir les valeurs des propriÃ©tÃ©s Â« model Â» et Â« attribute Â» ou Â« name Â».',
    'About us'=>'Qui sommes-nous?',
    'Contact'=>'Contacts',
    'Read More'=>'Voir plus',
    'Login'=>'Entrar',
    'Logout ('.Yii::app()->user->name.')'=>'Salir ('.Yii::app()->user->name.')',
    'Bookings'=>'Réservations',
    'Testimonials'=>'Témoignages',
    'Photos'=>'Photos',
    'Places'=>'Sitios de Interes',
    'Accommodations'=>'Logements',
    'Share this site with your friends'=>'Partagez ce site avec vos amis.',
    'Tours'=>'Excursions',
    'The best way to explore Cuba.'=>'Le meilleur type d’hébergement à Cuba.',
    'Matanzas, Cárdenas, & Varadero'=>'La Visite à Matanzas, Cárdenas, et Varadero',
    'Havana day tour'=>'Une journée à la Havane',
    'Trinidad & Cienfuegos '=>'Trinidad-et-Cienfuegos',
    'Three cities tour'=>'Excursions en trois villes',
    'Guama and the Bay of Pigs' => 'Guama et la Baie des Cochons',
    'Havana & Tropicana '=>'La Havane et Le Tropicana',
    'Havana and the cannon shot'=>'La Havane et le coup de canon',
    'Just tell us your choices and we will do the rest.'=>'Faites juste votre choix et nous nous occupons du reste.',
    'Some images of Cuba.'=>'Quelques images de Cuba.',
    'Your opinion means a lot to us.'=>'Votre opinion compte beaucoup pour nous.',
    'The best place to enjoy your stay.'=>'Le meilleur endroit pour profiter de votre séjour.',
    'Get to know who we are.'=>'En savoir plus sur nous.',
    'Keep in touch. You are our commitment.'=>'Gardons le contact. Nous sommes à votre écoute.',
    'Find us on Tripadvisor'=>'Retrouvez-nous sur Tripadvisor.',
    'People are very happy with our work. Get to know their opinion.'=>'Nos clients s’en vont toujours satisfaits; voyez leurs impressions.' ,
    'All Rights Reserved.'=>'Tous Droits Réservés.',
    'Transfers'=>'Transferts',
    'Follow us on Facebook'=>'Rejoignez-nous sur Facebook',
    'Book tour'=>'Réserver',
    'Create'=>'Créer',
    );
